### ISSUE TITLE
Добавить зависимости

### ISSUE THREAD

**Issue by yaphtes** [Yaphtes/course_work#6]
Добавить зависимость:
количество электронов от количества используемых ядер и отобразить её(зависимость) в виде времени выполнения программы.

100 электронов : 1 узел
100 электронов : 5 узлов
100 электронов : 15 узлов
100 электронов : 24 узла

250 электронов : 1 узел
250 электронов : 5 узлов
250 электронов : 15 узлов
250 электронов : 24 узла

500 электронов : 1 узел
500 электронов : 5 узлов
500 электронов : 15 узлов
500 электронов : 24 узла

**Comment by modelflat** [comment]
Более не актуально, так как добавлены скрипты для проверки производительности.
